"use client";

import { useState } from "react";
import type { ImpactMetric } from "@/lib/measurement/types";
import type { CalculatedValueModel, EconomicSummary } from "@/lib/economic-impact/types";
import { EconomicImpactSection } from "./economic-impact-section";
import { formatDate, formatMeasure, resultLabel } from "@/lib/measurement/format";

export function ImpactWorkspace({ metrics, initialId, valueModels, economicSummary }: { metrics: ImpactMetric[]; initialId?: string; valueModels: CalculatedValueModel[]; economicSummary: EconomicSummary }) {
  const [selectedId, setSelectedId] = useState(initialId ?? metrics[0]?.id ?? "");
  const selected = metrics.find((metric) => metric.id === selectedId) ?? metrics[0];
  return <main className="content intelligence-content">
    <header className="intelligence-header"><div><p className="intelligence-context">Baseline → expected improvement → actual result</p><h1>Impact</h1><p>Follow the measures behind each improvement. A result only appears when its observation and evidence have been verified.</p></div><span>{metrics[0]?.demo ? "Northstar Manufacturing · Demo examples" : "Your organization · Shared measures"}</span></header>
    <EconomicImpactSection models={valueModels} summary={economicSummary}/>
    {metrics.length === 0 ? <section className="intelligence-empty"><h2>No measures shared yet</h2><p>Delaro will add a baseline, target, method, and evidence source before results appear here.</p></section> :
      <div className="impact-layout"><section aria-label="Impact measures" className="impact-list"><div className="intelligence-index-title"><span>Measures being tracked</span><span>{String(metrics.length).padStart(2, "0")}</span></div>{metrics.map((metric) => <button type="button" key={metric.id} className={`impact-item ${selected?.id === metric.id ? "is-selected" : ""}`} aria-pressed={selected?.id === metric.id} onClick={() => setSelectedId(metric.id)}><span className="impact-item-heading"><strong>{metric.name}</strong><small>{metric.demo ? "Demo example" : metric.currentValue === null ? "Evidence pending" : "Verified"}</small></span><span className="impact-value-line"><span><small>Baseline</small><strong>{formatMeasure(metric.baselineValue, metric.unit)}</strong></span><b aria-hidden="true">→</b><span><small>Expected</small><strong>{formatMeasure(metric.targetValue, metric.unit)}</strong></span><b aria-hidden="true">→</b><span><small>Current</small><strong>{formatMeasure(metric.currentValue, metric.unit)}</strong></span></span></button>)}</section>
        {selected && <aside className="impact-inspector" aria-label="Measure details"><div className="impact-inspector-title"><span>Measurement record</span><strong>{resultLabel(selected)}</strong></div><h2>{selected.name}</h2><p>{selected.description ?? "Description not yet provided."}</p><div className="impact-value-summary"><div><span>Baseline</span><strong>{formatMeasure(selected.baselineValue, selected.unit)}</strong><small>{selected.baselineStatus === "verified" ? "Verified baseline" : "Evidence pending"}</small></div><div><span>Expected</span><strong>{formatMeasure(selected.targetValue, selected.unit)}</strong><small>Target</small></div><div><span>Current</span><strong>{formatMeasure(selected.currentValue, selected.unit)}</strong><small>{resultLabel(selected)}</small></div></div><dl className="impact-facts"><div><dt>Measurement period</dt><dd>{selected.measurementPeriod ?? selected.baselinePeriod ?? "Not measured"}</dd></div><div><dt>Source</dt><dd>{selected.source ?? "Not provided"}</dd></div><div><dt>Evidence confidence</dt><dd>{selected.currentValue === null ? "Pending verified observation" : selected.evidenceConfidence}</dd></div><div><dt>Last measured</dt><dd>{formatDate(selected.lastMeasuredAt)}</dd></div><div><dt>Method</dt><dd>{selected.measurementMethod ?? "Not specified"}</dd></div><div><dt>Cadence</dt><dd>{selected.cadence ?? "Not specified"}</dd></div><div><dt>Owner</dt><dd>{selected.ownerName ?? "Not assigned"}</dd></div><div><dt>Evidence</dt><dd>{selected.evidenceDescription ?? "No verified evidence attached"}{selected.evidenceUrl && <a href={selected.evidenceUrl} target="_blank" rel="noopener noreferrer">Open evidence ↗</a>}</dd></div></dl>{selected.demo && <p className="impact-demo-note">Illustrative demo values. Baselines are estimates pending evidence; no actual result has been entered.</p>}</aside>}
      </div>}
  </main>;
}
