-- Private per-tenant client files. No public URL or service-role key is used.
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('client-documents','client-documents',false,10485760,
  array['application/pdf','image/png','image/jpeg',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])
on conflict (id) do nothing;

create table public.client_documents (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  storage_path text not null unique,
  file_name text not null check (length(trim(file_name)) between 1 and 180),
  mime_type text not null,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 10485760),
  description text,
  visibility text not null default 'client' check (visibility in ('client','internal')),
  uploaded_by_membership_id uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id,id),
  check (storage_path like organization_id::text || '/%'),
  foreign key (organization_id,uploaded_by_membership_id)
    references public.organization_memberships(organization_id,id) on delete restrict
);
create index client_documents_organization_created_idx
  on public.client_documents (organization_id,created_at desc);
create trigger client_documents_updated_at before update on public.client_documents
  for each row execute function public.set_updated_at();
alter table public.client_documents enable row level security;
revoke all on public.client_documents from anon,authenticated;
grant select,insert,update on public.client_documents to authenticated;

create policy "Members read shared client documents" on public.client_documents for select to authenticated
  using (visibility='client' and public.is_org_member(organization_id));
create policy "Delaro reads private client documents" on public.client_documents for select to authenticated
  using (public.has_org_role(organization_id,array['delaro_admin','delaro_consultant']::public.organization_member_role[]));
create policy "Active contributors register documents" on public.client_documents for insert to authenticated
  with check (
    exists (select 1 from public.organization_memberships m
      where m.organization_id=client_documents.organization_id
        and m.id=client_documents.uploaded_by_membership_id
        and m.user_id=(select auth.uid()) and m.status='active'
        and m.role in ('delaro_admin','delaro_consultant','client_admin','client_user'))
    and (visibility='client' or public.has_org_role(organization_id,
      array['delaro_admin','delaro_consultant']::public.organization_member_role[]))
  );
create policy "Delaro updates document publication" on public.client_documents for update to authenticated
  using (public.has_org_role(organization_id,array['delaro_admin','delaro_consultant']::public.organization_member_role[]))
  with check (public.has_org_role(organization_id,array['delaro_admin','delaro_consultant']::public.organization_member_role[]));

-- The storage path is generated by the server: organization UUID / object UUID.extension.
create policy "Active contributors upload tenant documents" on storage.objects for insert to authenticated
  with check (bucket_id='client-documents'
    and name ~ '^[0-9a-f-]{36}/[0-9a-f-]{36}\.[a-z0-9]+$'
    and exists (select 1 from public.organization_memberships m
      where m.organization_id::text=(storage.foldername(name))[1]
        and m.user_id=(select auth.uid()) and m.status='active'
        and m.role in ('delaro_admin','delaro_consultant','client_admin','client_user')));
create policy "Authorized members download registered documents" on storage.objects for select to authenticated
  using (bucket_id='client-documents'
    and exists (select 1 from public.client_documents d
      where d.storage_path=name and d.organization_id::text=(storage.foldername(name))[1]));
create policy "Delaro may clean up tenant document objects" on storage.objects for delete to authenticated
  using (bucket_id='client-documents'
    and exists (select 1 from public.organization_memberships m
      where m.organization_id::text=(storage.foldername(name))[1]
        and m.user_id=(select auth.uid()) and m.status='active'
        and m.role in ('delaro_admin','delaro_consultant')));
